# Generated by Django 3.0.1 on 2020-01-25 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherprofile',
            name='address',
            field=models.TextField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='contact_no',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='subject',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
