# Generated by Django 3.0.1 on 2020-01-26 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_auto_20200126_0027'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='approval_status',
            field=models.CharField(choices=[('APPROVED', 'Approved'), ('PENDING', 'Pending'), ('REJECTED', 'Rejected')], default='Pending', max_length=8),
        ),
    ]
